version: '3.8'

services:
  freeradius:
    image: ghcr.io/glassrom/freeradius-docker:master
    read_only: true
    container_name: freeradius
    user: "970:970"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - "1812:1812/udp"
      - "1812:1812/tcp"
      - "1813:1813/udp"
      - "1813:1813/tcp"
    pull_policy: always
    volumes:
      - type: bind
        source: /etc/raddb/certs/server.crt
        target: /etc/raddb/certs/server.crt
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: /etc/raddb/certs/server.pem
        target: /etc/raddb/certs/server.pem
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: /etc/raddb/certs/ca.pem
        target: /etc/raddb/certs/ca.pem
        read_only: true
        bind:
          selinux: z
      - type: bind
        source: /etc/raddb/clients.conf
        target: /etc/raddb/clients.conf
        read_only: true
        bind:
          selinux: z
      # gvisor DNS fixup
      - type: bind
        source: /etc/resolv-container-freeradius.conf
        target: /etc/resolv.conf
        read_only: true
        bind:
          selinux: z
    tmpfs:
      - /tmp:nosuid,nodev,noexec
    restart: always
    depends_on:
      - unbound-freeradius
    networks:
      - freeradius_net
    runtime: runsc-overlay-host-network-nodirectfs

  unbound-freeradius:
    runtime: runsc-overlay-host-network-nodirectfs
    image: ghcr.io/glassrom/dns-docker:master
    read_only: true
    container_name: unbound-freeradius
    user: "970:970"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_RESOURCE
      - CAP_NET_RAW
    tmpfs:
      - /tmp:nosuid,nodev,noexec
    restart: always
    pull_policy: always
    networks:
      freeradius_net:
        ipv4_address: 172.19.0.2

networks:
  freeradius_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
